### ISSUE TITLE
Bug in alignment of phased sequences

### ISSUE THREAD

**Issue by brunoasm** [AntonelliLab/seqcap_processor#12]
Hi, I found a bug that was mixing sample names during the alignment of phased sequences

The bug shows up if a sequence name ends with a digit and traced it to line 245 of [align_sequences.py](seqcap_processor/secapr/align_sequences.py):

```python
string_to_replace = '%s_'%str(locus_name)
t.id = rest_of_string.replace(string_to_replace, '')
```

As currently written, let's say one has a sequence named BM1842 for locus #2. In the joined file, the alleles will be named as `2_BM1842_0 | 2` and `2_BM1842_1 | 2`.
The intended behavior is to remove `2_` at the start, resulting in names `BM1842_0` and `BM1842_1`.
The actual result in this case will be `BM1840` and `BM1841`. In my case, there other samples with these IDs, so one can imagine the severity of the problem.

I fixed it by limiting the number of replacements to 1:
```python
t.id = rest_of_string.replace(string_to_replace, '', 1)
```

But maybe using a regex search anchored at the start of the string would be safer

**Comment by tobiashofmann88** [comment]
Thanks a lot Bruno for reporting this issue and finding a solution! I did as you said and implemented a replacement search anchored at the beginning of the string in order to avoid this issue in the future.
Let me know if you run into any more problems!

Best,
Tobi

------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by brunoasm** [comment]
great, thanks @tobiashofmann88!

**Comment by tobiashofmann88** [comment]
p.s. the update and some other new features are now available in the newest coda release of secapr (v.1.1.14).
I also added some instruction to the end of the secapr installation tutorial about how to update to the GitHub development version, which usually is the most up to date.


------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------
