### ISSUE TITLE
Assembly_reads fails with IOError

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [AntonelliLab/seqcap_processor#13]
I am trying to assemble our cleaned reads using the assemble-reads function and run into the following error:

`>(secapr_env) sysbot@ug-ubgb900-c119:/media/sysbot/Daten/Niklas/SECAPR_Zanth/data/processed/trimmed$ secapr assemble_reads --input /media/sysbot/Daten/Niklas/SECAPR_Zanth/data/processed/trimmed/ --output /media/sysbot/Daten/Niklas/SECAPR_Zanth/data/processed/assembled/
>##################################################
>Processing sample Zcori
>Traceback (most recent call last):
>File "/usr/local/anaconda3/envs/secapr_env/bin/secapr", line 6, in <module> sys.exit(secapr.__main__.main())
>File "/usr/local/anaconda3/envs/secapr_env/lib/python2.7/site-packages/secapr/__main__.py", line 50, in main
    args.func(args)
>File "/usr/local/anaconda3/envs/secapr_env/lib/python2.7/site-packages/secapr/assemble_reads.py", line 146, in main
    contig_count_df = get_stats_abyss(sample_output_folder,sample_id,sample_contig_count_dict)
>File "/usr/local/anaconda3/envs/secapr_env/lib/python2.7/site-packages/secapr/assemble_reads.py", line 251, in get_stats_abyss
    contig_count = count_contigs(contig_file)
>File "/usr/local/anaconda3/envs/secapr_env/lib/python2.7/site-packages/secapr/assemble_reads.py", line 245, in count_contigs
    return sum([1 for line in open(contig, 'rU').readlines() if line.startswith('>')])
>IOError: [Errno 2] No such file or directory: '/media/sysbot/Daten/Niklas/SECAPR_Zanth/data/processed/assembled/Zcori.fa'

Secpar (including abyss) was installed via conda on a Ubuntu 14.04 system. Also in the function there is no option to specify the --assembler parameter. Could there be some error in the installation?
If not could you please help me identify the problem?
Thank you.

**Comment by tobiashofmann88** [comment]
It might be that you somehow installed an outdated version of the software.
What response do you get when you type ’secapr —version’?


------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by ClaudiaPaetzold** [comment]
secapr --version prints
> secapr 1.1.4

running conda update secapr tells me that all requested packages are already installed.

I have also tested Abyss separately and it runs through a representative sample without error. Also the IOError appears very fast (within seconds of starting the script). The requested outfolders (in this case "assembled/" and "assembled/stats/Zcori") are created, but there is no fasta file in there.

Thank you for your quick response and your help.

**Comment by tobiashofmann88** [comment]
somehow you have a very outdated version of secapr installed.
just type ’conda update secapr’ to update the pipeline to its newest version.


------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by ClaudiaPaetzold** [comment]
I have tried to run conda update both with activated and deactivated secapr environment. 

I all cases the result is 

# All requested packages already installed.

I have added all required channels to conda; the environments and package metadata checks come out with no error. I am working on a Ubuntu 16.04 machine and conda 4.6.3.

**Comment by tobiashofmann88** [comment]
That is strange.
What happens if you type “conda install secapr=1.1.12”?
Best,
Tobi
------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by ClaudiaPaetzold** [comment]
I tried that, and shot my Anaconda installation. After I rescued it, I reupdated my conda base, then activated the env and tried the update again. Got an error:

>ERROR conda.core.link:_execute(544): An error occurred while installing package 'defaults::dbus-1.10.20-0'. 

So then I changes permissions for the package: 
> chmod +r /usr/local/anaconda3/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh
> chmod +r /usr/local/anaconda3/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper

Then I tried the conda install again. Now it seems to work. It's running trough the first sample as I write
Thank you for your help.
Cheers

**Comment by tobiashofmann88** [comment]
great!
otherwise if it is still causing problems you can follow the instructions at the end of the secapr installation tutorial. I added a paragraph there how to update to the development version, which gives you all the most recent upgrades.
Best,
Tobi
------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by tobiashofmann88** [comment]
p.s.: i just made a new secapr release on conda with some updates, it’s called v.1.1.14 and should install and run smoother than previous versions.

Best,
Tobi

------------------------------------------------------
Tobias Andermann (Hofmann)
PhD student
Biological and Environmental Sciences, University of Gothenburg
The Antonelli Lab <http://antonelli-lab.net/> | Gothenburg Global Biodiversity Centre <http://ggbc.gu.se/>
Carl Skottsbergs gata 22 B <https://goo.gl/maps/mwGPq3HNzAN2>, 413 19 Göteborg
tobias.andermann@bioenv.gu.se <mailto:tobias.andermann@bioenv.gu.se>
+46 76 090 1106
github.com/tobiashofmann88 <https://github.com/tobiashofmann88>
Google Scholar profile <https://scholar.google.se/citations?user=soeWAQwAAAAJ&hl=en&oi=ao>
------------------------------------------------------

**Comment by ClaudiaPaetzold** [comment]
Thanks a lot;
I will update right away. 
And I will close the issue now, as my analysis does run smoothly now.

Best,
Claudia
